name: violet
description: A workshop flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  health: ^6.0.0
  flutter_hooks: ^0.18.6
  geolocator: ^9.0.2
  lottie: ^2.3.2
  google_maps_flutter: ^2.2.6
  google_fonts: ^4.0.4
  animated_notch_bottom_bar: ^0.0.6
  go_router: ^7.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.1
  dio: ^5.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  permission_handler: ^10.2.0
  faker: ^2.1.0
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - .env
    - .env.example
